admin_keys:
  florent: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPKhvfzK+ISFmnAJOOhnaqziJ1uYPU23p8qiEw4XF9+M"
  lucas: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKf1pKT3a6KPepMwESP30xcaQURksQCTs+fShCzFkARQ"
  antoine: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILFzXQ+efxs/ngSHF+n0p79byamEFM9CKViLQsdA0APv"
  dmitry: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBLJPRMyYgVA4MF5Je2FRmQIIkGPxniCZHJNl6iRkrKg"
