---
- name: Install firefox
  ansible.builtin.package:
    name: firefox-esr
    state: present

- name: Configure Firefox policies
  firefox_policies:
    path: /usr/lib/firefox-esr/distribution/policies.json
    policies: "{{ firefox_policies | ansible.builtin.combine(firefox_policies_extra, recursive=True) }}"
