---
firefox_extension_id: "odoo-addon@superquinquin-sur-deule.org"
firefox_extension_dir: "/usr/share/firefox-esr/distribution/extensions/{{ firefox_extension_id }}"

firefox_extension_manifest:
  manifest_version: 3
  name: "Odoo Addon"
  version: "{{ now(fmt='%y%m%d.%H%M%S') }}"
  browser_specific_settings:
    gecko:
      id: "{{ firefox_extension_id }}"
  content_scripts:
    - matches:
        - "https://*.superquinquin.fr/*"
        - "https://*.foodcoop12.trobz.com/*"
        - "https://*.foodcoop18.trobz.com/*"
      js:
        - content.js
      run_at: document_idle

firefox_extension_policies:
  Preferences:
    xpinstall.signatures.required: false
  ExtensionSettings: >-
    {{ {
      firefox_extension_id: {
        "installation_mode": "force_installed",
        "install_url": "file://" ~ firefox_extension_dir ~ ".xpi"
      }
    } }}
