---
- name: Reload udev rules
  ansible.builtin.shell: |
    udevadm control --reload-rules && \
    udevadm trigger --subsystem-match=block
  listen: reload-udev-rules

- name: Create tmpfiles
  ansible.builtin.shell: systemd-tmpfiles --create
  listen: create-tmpfiles

- name: Restart systemd-journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted
  listen: restart-journald

- name: Apply sysctl configuration
  ansible.builtin.shell: sysctl -p /etc/sysctl.d/*.conf
  listen: apply-sysctl
