---
- name: Set hostname from inventory
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Synchronize /etc/hosts with new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ ansible_hostname }}"
    state: present
