---
- name: Deploy udev scheduler rules
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/60-scheduler.rules
    mode: "0644"
    content: |
      ACTION=="add|change", SUBSYSTEM=="block", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
      ACTION=="add|change", SUBSYSTEM=="block", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"
  notify: reload-udev-rules

- name: Configure sysctl settings
  ansible.builtin.copy:
    dest: "/etc/sysctl.d/{{ item.name }}"
    mode: "0644"
    content: |
      {% for key, value in item.parameters.items() %}
      {{ key }} = {{ value }}
      {% endfor %}
  loop: "{{ sysctl_settings }}"
  notify: apply-sysctl
