---
sysctl_settings:
  - name: 99-kiosk.conf
    parameters:
      vm.dirty_ratio: "10"
      vm.swappiness: "10"
      vm.vfs_cache_pressure: "50"
      kernel.panic: "10"
  - name: 99-kiosk-security.conf
    parameters:
      net.ipv4.ip_forward: "0"
      net.ipv4.conf.all.send_redirects: "0"
      net.ipv4.tcp_syncookies: "1"
      net.ipv4.icmp_echo_ignore_all: "0"
      kernel.kptr_restrict: "2"
      kernel.dmesg_restrict: "1"
      kernel.printk: "3 3 3 3"
      fs.suid_dumpable: "0"
